### Numpy
is a python library used for working with arrays.

spiPy.org

In [1]:
import numpy as np
a=np.array([[2.0,5,6.0,3.0],[2.5,5.4,2,3.0]])#2d array
b=np.array([1,5,7,4]) #1d array
a.ndim


2

In [2]:
c=np.array([1,2,3])
c.ndim

1

In [3]:
a

array([[2. , 5. , 6. , 3. ],
       [2.5, 5.4, 2. , 3. ]])

In [4]:
 a.shape
#2 rows and 4 col

(2, 4)

In [5]:
#type
a.dtype

dtype('float64')

In [6]:
b.dtype

dtype('int32')

In [7]:
#if we want to specify what type we wanted to store ,we didnt have big values so we would take less size
b=np.array([1,5,7,4], dtype='int8')

In [8]:
b.dtype

dtype('int8')

### Accessing / Changing specific elements,rows,columns,etc

In [9]:
a=np.array([[1,2,3,4,5,0,7],[11,12,13,14,15,16,17]])
a

array([[ 1,  2,  3,  4,  5,  0,  7],
       [11, 12, 13, 14, 15, 16, 17]])

In [10]:
a.shape #rand c

(2, 7)

In [11]:
#get a specific element(r,c)
a[1,2] 

13

In [12]:
a[0,6] #r and that element 

7

In [13]:
#using negative notation
a[1,-6] 

12

In [14]:
#get column
a[:,3]    #all rows and 4th column

array([ 4, 14])

In [15]:
#get row
a[0]

array([1, 2, 3, 4, 5, 0, 7])

In [16]:
#start index:end idex :stepsize
a[0,1:5:2]

array([2, 4])

In [17]:
a[0,1:-3:1]

array([2, 3, 4])

In [18]:
#change speific element
a[0,4]=67
a

array([[ 1,  2,  3,  4, 67,  0,  7],
       [11, 12, 13, 14, 15, 16, 17]])

In [19]:
a[:,2]=100
a

array([[  1,   2, 100,   4,  67,   0,   7],
       [ 11,  12, 100,  14,  15,  16,  17]])

In [20]:
a[1:2]=178
a

array([[  1,   2, 100,   4,  67,   0,   7],
       [178, 178, 178, 178, 178, 178, 178]])

In [21]:
b=np.array([[[1,2, 100],[4,67,6]], [[11,12,100],[1,6,8]]])
b

array([[[  1,   2, 100],
        [  4,  67,   6]],

       [[ 11,  12, 100],
        [  1,   6,   8]]])

In [22]:
b[0,1,2]

6

In [23]:
b[1,0,2]

100

In [24]:
b=np.array([[[1,2, 100],[4,67,6]],[[1,2, 100],[4,67,6]], [[11,12,100],[1,6,8]]])
b

array([[[  1,   2, 100],
        [  4,  67,   6]],

       [[  1,   2, 100],
        [  4,  67,   6]],

       [[ 11,  12, 100],
        [  1,   6,   8]]])

In [25]:
b[2,0,1]

12

In [26]:
b=np.array([[[1,2, 100],[4,67,6]],[[1,2, 100],[4,67,6]], [[11,12,100],[1,6,8]], [[111,120,100],[17,64,8]]])
b

array([[[  1,   2, 100],
        [  4,  67,   6]],

       [[  1,   2, 100],
        [  4,  67,   6]],

       [[ 11,  12, 100],
        [  1,   6,   8]],

       [[111, 120, 100],
        [ 17,  64,   8]]])

In [27]:
b[3,0,1]

120

### Initilizing differnt types of arrays

In [28]:
#initilize allzeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros((2,1,5)) #3d 

array([[[0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.]]])

In [30]:
np.zeros((3,2,3,2)) #4d


array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [31]:
b=np.ones((4,2,2))#, dtype='int32')
b

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [32]:
b.dtype

dtype('float64')

In [33]:
c=np.ones((4,2,2), dtype='int32')
c

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [34]:
c.dtype

dtype('int32')

In [35]:
#any other number
#np.full(shape,value)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [36]:
np.full((2,3),12)

array([[12, 12, 12],
       [12, 12, 12]])

In [37]:
#random numbers
np.random.rand(2,3)

array([[0.38758976, 0.84280458, 0.18177164],
       [0.82487752, 0.63567748, 0.36474627]])

In [38]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
#repeat
a=np.array([[1,2,3]]) #2d-
r=np.repeat(a,3,axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
a=np.ones((5,5))
a


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
b=np.zeros((5,5))
b[1,1]=9
b

array([[0., 0., 0., 0., 0.],
       [0., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
v=np.array([[[1,2],[3,9]],[[29,7],[8,6]]])      #3d
v

array([[[ 1,  2],
        [ 3,  9]],

       [[29,  7],
        [ 8,  6]]])

In [43]:
v.shape

(2, 2, 2)

In [44]:
b=np.array([[[1,2],[3,9]],[[29,7],[8,6]]])       #3d
b

array([[[ 1,  2],
        [ 3,  9]],

       [[29,  7],
        [ 8,  6]]])

In [45]:
b.shape

(2, 2, 2)

In [46]:
lspace=np.linspace(1,5,3)
lspace

array([1., 3., 5.])

In [47]:
#axis0 column axis1 row
x=np.array([12,5,9,7,78])
x.argmax() #it gaves the index of number which is maximum 


4

In [48]:
x.argmin()
x.argsort() #it gaves the index of array element so that according to that index our array is sorted

array([1, 3, 2, 0, 4], dtype=int64)

In [49]:
y=np.array([[1,2,3],[4,622,7],[8,9,11]])
y

array([[  1,   2,   3],
       [  4, 622,   7],
       [  8,   9,  11]])

In [50]:
y.flat
for item in y.flat:
    print(item)

1
2
3
4
622
7
8
9
11


In [51]:
y.sum(axis=0) #sum of col (in form of array)

array([ 13, 633,  21])

In [52]:
y.sum(axis=1) 

array([  6, 633,  28])

In [53]:
y.T #Transpose

array([[  1,   4,   8],
       [  2, 622,   9],
       [  3,   7,  11]])

In [54]:
y.nbytes

36

In [55]:
y.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [56]:
y.ravel()

array([  1,   2,   3,   4, 622,   7,   8,   9,  11])

In [57]:
y.reshape((9,))

array([  1,   2,   3,   4, 622,   7,   8,   9,  11])

In [58]:
y.reshape((9,1))

array([[  1],
       [  2],
       [  3],
       [  4],
       [622],
       [  7],
       [  8],
       [  9],
       [ 11]])

In [59]:
y

array([[  1,   2,   3],
       [  4, 622,   7],
       [  8,   9,  11]])

In [60]:
z=np.array([[1,2,3],[4,2,7],[8,9,11]])
z

array([[ 1,  2,  3],
       [ 4,  2,  7],
       [ 8,  9, 11]])

In [61]:
y+z

array([[  2,   4,   6],
       [  8, 624,  14],
       [ 16,  18,  22]])

#### This will not happen in list

In [62]:
[1,2,3]+[1,2,3]

[1, 2, 3, 1, 2, 3]

In [63]:
y*z

array([[   1,    4,    9],
       [  16, 1244,   49],
       [  64,   81,  121]])

In [64]:
p=np.array([[1,2,3],[1,22,3],[1,2,3]])
q=np.array([4,5,6])
p


array([[ 1,  2,  3],
       [ 1, 22,  3],
       [ 1,  2,  3]])

In [65]:
p.T

array([[ 1,  1,  1],
       [ 2, 22,  2],
       [ 3,  3,  3]])

In [66]:
p+q

array([[ 5,  7,  9],
       [ 5, 27,  9],
       [ 5,  7,  9]])

In [67]:
p*q

array([[  4,  10,  18],
       [  4, 110,  18],
       [  4,  10,  18]])

In [68]:
p.ndim

2

In [69]:
np.sqrt(p) #square root

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 4.69041576, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [70]:
o=np.where(p>5)
o

(array([1], dtype=int64), array([1], dtype=int64))

### How numpy takes less space

In [71]:
import sys

In [72]:
c=[0,4,55,2]  #python array

In [73]:
np=np.array(c) #numpy array

In [74]:
sys.getsizeof(1)*len(c) #size of python array and size of 1 element and *len of python array

112

In [75]:
np.itemsize*np.size  #size of numpy array and size of 1 item * len of array 

16

In [76]:
w=([[1,3,2,4,5],[7,40,4,55,2]])
w

[[1, 3, 2, 4, 5], [7, 40, 4, 55, 2]]

In [77]:
sys.getsizeof(1)*len(w)

56