### Python Pandas 


1.Pandas dataframe

2.Pandas series

3.Pandas basic operations

In [2]:
import pandas as pd
import numpy as np

In [9]:
np.arange(0,20).reshape(5,4) #2d data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
# create above data to Dataframe 
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])
#                data 
#                                             index name (by default it is 1,2,3...so on)
#                                                                                           column

In [14]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4),columns=['col1','col2','col3','col4'])

col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19

In [19]:
pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'])

0   1   2   3
row1   0   1   2   3
row2   4   5   6   7
row3   8   9  10  11
row4  12  13  14  15
row5  16  17  18  19

In [20]:
df.head(2)

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7

In [21]:
df.tail(3)

col1  col2  col3  col4
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    5 non-null      int32
 1   col2    5 non-null      int32
 2   col3    5 non-null      int32
 3   col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [25]:
df.describe()

col1       col2       col3       col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

### Indexing

In [31]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

### By column name

In [40]:
df[['col1','col2','col3']] #use nested list when there are multiple columns

col1  col2  col3
row1     0     1     2
row2     4     5     6
row3     8     9    10
row4    12    13    14
row5    16    17    18

In [35]:
type(df[['col1','col2','col3']])

pandas.core.frame.DataFrame

In [33]:
df['col3']

row1     2
row2     6
row3    10
row4    14
row5    18
Name: col3, dtype: int32

In [34]:
type(df['col3'])

pandas.core.series.Series

### Row indexing

In [41]:
#Row index name (loc)
df.loc[['row2','row1']]

col1  col2  col3  col4
row2     4     5     6     7
row1     0     1     2     3

In [42]:
#combining row and col using iloc
df.iloc[2:4,0:2]

col1  col2
row3     8     9
row4    12    13

In [45]:
df.iloc[:,1] #all rows and 1st col

row1     1
row2     5
row3     9
row4    13
row5    17
Name: col2, dtype: int32

In [46]:
df.iloc[2,:] #all columns and 2nd row

col1     8
col2     9
col3    10
col4    11
Name: row3, dtype: int32

In [51]:
df.iloc[:,1:]

col2  col3  col4
row1     1     2     3
row2     5     6     7
row3     9    10    11
row4    13    14    15
row5    17    18    19

In [48]:
df

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [54]:
#convert dataframe into arrays
df.iloc[:,2:].values

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

### Basic Operations

In [56]:
df.isnull()

col1   col2   col3   col4
row1  False  False  False  False
row2  False  False  False  False
row3  False  False  False  False
row4  False  False  False  False
row5  False  False  False  False

In [59]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,2,6]],index=['row1','row2'],columns=['col1','col2','col3'])
##                   multiple row so [[]]
df

col1  col2  col3
row1     1   NaN     2
row2     1   2.0     6

In [64]:
#df.isnull().sum()
#or
df.isnull()

col1   col2   col3
row1  False   True  False
row2  False  False  False

In [66]:
df.values

array([[ 1., nan,  2.],
       [ 1.,  2.,  6.]])

AttributeError: 'DataFrame' object has no attribute 'unique'